### ISSUE TITLE
app_info != NULL errors

### ISSUE THREAD

**Issue by hadess** [Kekun/gnome-games#165]
```
** (gnome-games:31487): CRITICAL **: games_desktop_tracker_query_check_categories: assertion 'app_info != NULL' failed

#0  0x00007ffff1d06683 in _g_log_abort (breakpoint=1) at gmessages.c:324
#1  g_logv (log_domain=0x0, log_level=G_LOG_LEVEL_CRITICAL, format=<optimized out>, args=args@entry=0x7fffffffd268) at gmessages.c:1081
#2  0x00007ffff1d067e2 in g_log (log_domain=log_domain@entry=0x0, log_level=log_level@entry=G_LOG_LEVEL_CRITICAL, format=format@entry=0x7ffff1d74db0 "%s: assertion '%s' failed") at gmessages.c:1119
#3  0x00007ffff1d06809 in g_return_if_fail_warning (log_domain=log_domain@entry=0x0, pretty_function=pretty_function@entry=0x431c80 <__func__.53743> "games_desktop_tracker_query_check_categories", 
    expression=expression@entry=0x431b4b "app_info != NULL") at gmessages.c:1128
#4  0x0000000000411df4 in games_desktop_tracker_query_check_categories (error=0x7fffffffd398, app_info=0x0, self=0x8aec50) at desktop/desktop-tracker-query.c:295
#5  games_desktop_tracker_query_real_game_for_cursor (base=0x8aec50, cursor=<optimized out>, error=0x99b710) at desktop/desktop-tracker-query.c:216
#6  0x00000000004287e9 in games_tracker_game_source_each_game_for_query_co (_data_=0x99b5a0) at tracker/tracker-game-source.c:544
#7  0x0000000000428a0d in games_tracker_game_source_each_game_for_query (self=<optimized out>, game_callback=<optimized out>, game_callback_target=<optimized out>, query=<optimized out>, 
    _callback_=_callback_@entry=0x428db0 <games_tracker_game_source_each_game_ready>, _user_data_=_user_data_@entry=0x8864f0) at tracker/tracker-game-source.c:419
#8  0x0000000000428d1b in games_tracker_game_source_real_each_game_co (_data_=0x8864f0) at tracker/tracker-game-source.c:373
#9  0x00007ffff7acae5d in g_simple_async_result_complete (simple=0x8867b0) at gsimpleasyncresult.c:801
#10 0x00007ffff7acaecc in complete_in_idle_cb (data=0x8867b0) at gsimpleasyncresult.c:813
#11 0x00007ffff1cffe8a in g_main_dispatch (context=0x67bf60) at gmain.c:3157
#12 g_main_context_dispatch (context=context@entry=0x67bf60) at gmain.c:3782
#13 0x00007ffff1d00278 in g_main_context_iterate (context=context@entry=0x67bf60, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3853
#14 0x00007ffff1d0031c in g_main_context_iteration (context=0x67bf60, context@entry=0x0, may_block=may_block@entry=1) at gmain.c:3914
#15 0x00007ffff7b00f9c in g_application_run (application=application@entry=0x670bc0, argc=argc@entry=1, argv=argv@entry=0x7fffffffd6b8) at gapplication.c:2311
#16 0x0000000000430a5e in _vala_main (args=0x7fffffffd6b8, args_length1=1) at main.c:44
#17 0x00007ffff16f9580 in __libc_start_main () from /lib64/libc.so.6
#18 0x000000000040d539 in _start ()

gdb) frame 5
#5  games_desktop_tracker_query_real_game_for_cursor (base=0x8aec50, cursor=<optimized out>, error=0x99b710) at desktop/desktop-tracker-query.c:216
216     games_desktop_tracker_query_check_categories (self, _tmp9_, &_inner_error_);
(gdb) p _tmp9_
$1 = (GDesktopAppInfo *) 0x0
(gdb) list
211     path = _tmp6_;
212     _tmp7_ = path;
213     _tmp8_ = g_desktop_app_info_new_from_filename (_tmp7_);
214     app_info = _tmp8_;
215     _tmp9_ = app_info;
216     games_desktop_tracker_query_check_categories (self, _tmp9_, &_inner_error_);
217     if (G_UNLIKELY (_inner_error_ != NULL)) {
218         g_propagate_error (error, _inner_error_);
219         _g_object_unref0 (app_info);
220         _g_free0 (path);
(gdb) p _tmp7_
$2 = (const gchar *) 0xa39e00 "/usr/share/applications/hwengine.desktop"
```

That file doesn't exist (I reinstalled the OS on another machine while keeping the same $HOME).

**Comment by Kekun** [comment]
Tracker listed a non existing file and we don't check its existence before opening it, we clearly should. We should also check that the AppInfo have been correctly created.
